---
title: 'NYT Bestsellers: 02 Comparing Gender and Genre'
author: "A.H. Wilhelm"
date: "8/22/2018"
output:
  html_document: default
  pdf_document: default
---


###I created two charts to compare Gender and Genre.

##Loading packages and data.

```{r loading, warning=F, message=F}
library(readr)
library(ggplot2)
library(forcats)
library(dplyr)
library(ggthemes) 
library(DT)
library(tidyr) 
library(stringr)

#create dataframes from new data files
df_nytinfo_weeks<-read.csv("data/output/nytinfo_weeks.csv")

```

##Create data sets for charts


```{r create_datasets, warning=F, message=F}

df_CatGen1<- df_nytinfo_weeks %>% 
  group_by(type, Category, author_gender) %>% 
  summarize(avg.weeks=mean(weeks),total.weeks=sum(weeks),book.count=n()) 

#Getting rid of some problem rows
df_CatGen1 <- df_CatGen1%>% 
  filter(!is.na(type)) 
df_CatGen1 <- df_CatGen1[-c(46), ]


df_CatGen2<- df_CatGen1 %>% 
  filter(author_gender %in% c("female","male"))%>% 
  select(Category, author_gender, book.count) %>% 
  spread(author_gender, book.count) %>% 
  mutate_all(funs(replace(., is.na(.), 0))) %>% 
  mutate(total=female+male)

df_CatGen3 <- df_CatGen1 %>% 
  filter(author_gender %in% c("female","male"))%>% 
  select(Category, author_gender, avg.weeks) %>% 
  spread(author_gender, avg.weeks) %>% 
  mutate_all(funs(replace(., is.na(.), 0))) %>% 
  mutate(avgtotal=female+male)

#add total books to avg weeks list.
df_CatGen2b<- df_CatGen2 %>%  
  select(Category, total)

df_CatGen4 <- left_join(df_CatGen3, df_CatGen2b, by="Category")

```

#Create chart 1
Compare genre and gender by total number of best sellers on the list.
```{r create_chart1, warning=F, message=F}
  ggplot(df_CatGen2,
         aes(x=female, 
             y=fct_reorder(Category, total))) +
  geom_segment(
    aes(x=female, 
        y=fct_reorder(Category, total),
        xend=male,
        yend=fct_reorder(Category, total)),
    color="gray50")+
  geom_point(aes(x=female, y=fct_reorder(Category, total)), color="#D8666D", size=3.5, alpha=0.7)+
  geom_point(aes(x=male, y=fct_reorder(Category, total)), color="#207178", size=3.5, alpha=0.5)+
  geom_point(aes(x=female, y=fct_reorder(Category, total)), size=1, alpha=0.5)+
  geom_point(aes(x=male, y=fct_reorder(Category, total)), size=1, alpha=0.5)+
  labs(x="Number of books on list", y="Book Genre",
       title="Fiction versus Non-, and Girls versus Boys",
       subtitle="Number of NYT bestseller books, by genre and author gender, 2008-2016",
       caption="Data from some source")+
  theme_minimal()+
  theme(
    panel.grid.major=element_blank(),
    panel.grid.minor=element_blank(),
    panel.background = element_rect(fill = NA, colour = NA),
    panel.grid.major.x=element_line(linetype="dashed",colour="gray"),
    panel.grid.major.y=element_line(size=5.5,color="gray95")
  )

```

##Create chart 2 
Compare genre and gender by how long they stay on the list.
```{r create_chart2, warning=F, message=F}
 ggplot(df_CatGen4,
          aes(x=female, 
              y=fct_reorder(Category, total))) +
     geom_segment(
       aes(x=female, 
           y=fct_reorder(Category, total),
           xend=male,
           yend=fct_reorder(Category, total)),
       color="gray50")+
     geom_point(aes(x=female, y=fct_reorder(Category, total)), color="#D8666D", size=3.5, alpha=0.7)+
     geom_point(aes(x=male, y=fct_reorder(Category, total)), color="#207178", size=3.5, alpha=0.5)+
     geom_point(aes(x=female, y=fct_reorder(Category, total)), size=1, alpha=0.5)+
     geom_point(aes(x=male, y=fct_reorder(Category, total)), size=1, alpha=0.5)+
     labs(x="Avg.number of weeks on list", y="Book Genre",
          title="Fiction versus Non-, and Girls versus Boys",
          subtitle="Average time on the NYT Bestseller list, by genre and gender, 2008-2016",
          caption="Data from some source")+
     theme_minimal()+
     theme(
       panel.grid.major=element_blank(),
       panel.grid.minor=element_blank(),
       panel.background = element_rect(fill = NA, colour = NA),
       panel.grid.major.x=element_line(linetype="dashed",colour="gray"),
       panel.grid.major.y=element_line(size=5.5,color="gray95")
     )
```

